# Generated by Django 4.1.2 on 2022-10-22 12:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.FileField(blank=True, null=True, upload_to='about/images', verbose_name='image')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
