# Generated by Django 4.1.2 on 2022-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bizimlə əlaqə', max_length=255, verbose_name='title')),
                ('map_src', models.CharField(blank=True, max_length=500, null=True, verbose_name='Map source')),
                ('contact', models.TextField(verbose_name='contact')),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('address', models.TextField(verbose_name='address')),
                ('email', models.TextField(verbose_name='email')),
                ('additional_contact', models.TextField(blank=True, null=True, verbose_name='additional contact')),
            ],
        ),
    ]
