# Generated by Django 4.1.2 on 2022-10-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactpagedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
