# Generated by Django 4.1.2 on 2022-10-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contactpagedata_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpagedata',
            name='additional_contact',
        ),
    ]
