version: '3'

services:
  postgres:
    container_name:  postgres-db-blog
    image: postgres:11
    ports:
      - "5432:5432" # Bind host port 5432 to PostgresSQL port 5432
    env_file: .env
    volumes:
      - ./pgdb:/var/lib/postgresql/data

  app:
    container_name: blog-task
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    restart: always
    links:
      - postgres
    depends_on:
      - "postgres"
    volumes:
      - ../../blog_task:/app
    command: bash -c " source /venv/bin/activate && python /app/manage.py makemigrations --noinput && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
